# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    deploygate(
      api_token: ENV['DEPLOYGATE_API_TOKEN'],
      user: ENV['DEPLOYGATE_USER'],
      apk: '../build/app/outputs/apk/release/app-release.apk',
      distribution_key: ENV['DEPLOYGATE_DISTRIBUTION_KEY']
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
